[project]
authors = ["Aleksandar <milicoa97@gmail.com>"]
channels = ["conda-forge"]
name = "food-tracking-etl"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
dbt-duckdb = ">=1.9.4,<2"
python = ">=3.12.0,<3.13"
